# Change these first
owner: HelSec # Your GitHub organization or username, where this repository lives
repo: uptime # The name of this repository

sites:
  - name: join page
    url: https://byte.flomembers.com/helsec/members/application
    method: GET

status-website:
  baseUrl: /uptime
  favicon: https://helsec.fi/favicon.png
  logoUrl: https://helsec.fi/assets/images/helsec_logo_white.svg
  name: uptime for HelSec
  introTitle: HelSec status page
  introMessage: 'check if a page is down, or use [GitHub ↗️](https://github.com/HelSec/uptime) to "Watch" and get notified'
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Home
      href: https://helsec.fi
